// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OptPart2D
List OptPart2D(std::vector<double> data1, std::vector<double> data2, double penalty, std::string type);
RcppExport SEXP _OptPartitioning2D_OptPart2D(SEXP data1SEXP, SEXP data2SEXP, SEXP penaltySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(OptPart2D(data1, data2, penalty, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptPartitioning2D_OptPart2D", (DL_FUNC) &_OptPartitioning2D_OptPart2D, 4},
    {NULL, NULL, 0}
};
/*
RcppExport void R_init_OptPartitioning2D(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
*/