# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title OptPart2D 
#'                                                                                                        
#' @description Optimal Partitioning and PELT algorithms for changepoints dimension 2                           
#'                                                                                                       
#' @param data1 vector of data1 to segment (a univariate time series).                                
#' @param data2 vector of data2 to segment (a univariate time series).                                
#' @param penalty value of penalty (a non-negative real number).                                        
#' @param type string defining the  algorithm ("null" = Optimal Partitioning, "pruning" = PELT).       
#'                                                                                                          
#' @return a list of 4 elements  = (changepoints, means1, means2, GlobalCost).                    
#'                                                                                                                                                                               #
#' @param changepoints vector of changepoints.                                                                   
#' @param means1 vector of successive means for data1.                                                           
#' @param means2 vector of successive means for data2.
#' @param globalCost value of global cost.       
#'             
#' @exemples 
#' OptPart2D(data1 = c(0,1,0,8,5), data2 = c(0,1,0,1,1), penalty = 2,  type = "null")                                                                                      
#' OptPart2D(data1 = c(0,1,0,8,5), data2 = c(0,1,0,1,1), penalty = 2,  type = "pruning")

OptPart2D <- function(data1, data2, penalty, type) {
    .Call(`_OptPartitioning2D_OptPart2D`, data1, data2, penalty, type)
}

