# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OptPatr2D <- function(data1, data2, penalty, type) {
    .Call(`_OptPartitioning2D_OptPatr2D`, data1, data2, penalty, type)
}

